### ISSUE TITLE
Cannot compare head version of ObjectVersionId

### ISSUE THREAD

**Issue by Mewel** [OCFL/ocfl-java#110]
Comparing the head version of ObjectVersionId leads to a NPE. ObjectVersionId#equals() should check versionNum for null values.

    @Test
    public void equalsVersionId() {
        assertEquals(ObjectVersionId.head("a"), ObjectVersionId.head("a"));
        assertNotEquals(ObjectVersionId.head("a"), ObjectVersionId.head("b"));
    }

**Comment by pwinckles** [comment]
@Mewel Thanks for the report! It's fixed in main. I'm not going to cut an immediate point-release though because I'm hoping to do a larger release sometime this coming week.

**Comment by pwinckles** [comment]
This is fixed in the 2.1.0 release that I just pushed out
