### ISSUE TITLE
Store file size in OCFL metadata

### ISSUE THREAD

**Issue by rsteph-de** [OCFL/ocfl-java#116]
There are certain use cases for size metadata in OCFL, e.g.
- directory listing / file inventory of an object
- calculation of storage size of an object
- provided a Content-Length Header when implementing a FileDownloadServlet based on an OCFL backend.

The straight forward implementation would simply treat the size as another fixity
as already mentioned in OCFL Community Extension 0009: Digest Algorithms
(https://ocfl.github.io/extensions/0009-digest-algorithms.html)

I'm going to create a Pull Request based on my current sample code for this.

If we can open the DigestAlgorithmn class for extension (make constructor public) it becomes easier to support other fixity values.

**Comment by pwinckles** [comment]
Work done in https://github.com/OCFL/ocfl-java/pull/117

Thanks for the PR! I'll try to get a release out today or tomorrow

**Comment by pwinckles** [comment]
Available in https://github.com/OCFL/ocfl-java/releases/tag/v2.2.0
