### ISSUE TITLE
OcflRepositoryBuilder internal API is private

### ISSUE THREAD

**Issue by Mewel** [OCFL/ocfl-java#123]
It would be nice to be able to extend the OcflRepositoryBuilder. I have my own Repository implementation, but I have no way of building it through the OcflRepositoryBuilder. My problem is that everything is private.

I don't really see a reason why. Would be nicer if everything is protected so I have a chance of extending the API.

**Comment by pwinckles** [comment]
@Mewel Sure. Would you like to open a PR?

**Comment by Mewel** [comment]
See #124

**Comment by pwinckles** [comment]
@Mewel Okay, I merged it. Due to the holidays, I don't expect to have time to get a release out for a couple weeks.

**Comment by pwinckles** [comment]
@Mewel Sorry of the delay. I just released this as 2.2.2. It should be in maven central shortly.
